#!/usr/bin/env python3
"""
Live Sleeper draft assistant.

Two modes, deliberately separated so that nothing slow or network-dependent
happens while you are on the clock:

  1. PREP (run once, before the draft) — builds a local cheat sheet of ranked,
     tiered players. Either generated by Claude with web research, or imported
     from a rankings CSV you downloaded (FantasyPros et al).

  2. LIVE (during the draft) — polls the draft and gives instant, offline
     recommendations. No API calls, no waiting. It knows exactly when your next
     two picks land and recommends against the wrap.

Setup:
    pip install anthropic requests          # anthropic only needed for --prep
    export ANTHROPIC_API_KEY="..."          # only needed for --prep

Prep (do this BEFORE the draft):
    python draft_assistant.py --prep --league-id LEAGUE_ID
    # or, from your own rankings file:
    python draft_assistant.py --prep --from-csv rankings.csv

Live:
    python draft_assistant.py --league-id LEAGUE_ID --my-username YOU
    python draft_assistant.py --draft-id DRAFT_ID --my-username YOU   # mock drafts

CSV format for --from-csv: a header row containing at least a name column and a
position column; rank and tier columns are used if present. Common header names
are auto-detected (name/player/player_name, pos/position, rank/rk/adp, tier).
"""

import argparse
import csv
import json
import os
import re
import sys
import time
from collections import Counter

import requests

BASE_URL = "https://api.sleeper.app/v1"
MODEL = "claude-opus-5"
FANTASY_POSITIONS = ("QB", "RB", "WR", "TE", "K", "DEF")
PLAYER_CACHE_PATH = os.path.expanduser("~/.cache/sleeper_players_nfl.json")
PLAYER_CACHE_MAX_AGE = 24 * 60 * 60
CHEATSHEET_PATH = "draft_cheatsheet.json"
BENCH_SLOTS = ("BN", "IR", "TAXI")
NAME_SUFFIXES = {"jr", "sr", "ii", "iii", "iv", "v"}

# Nicknames rankings sites use that differ from the legal name Sleeper stores.
# Punctuation and initials are already handled by normalize_name ("A.J. Brown"
# and "AJ Brown" both reduce to "aj brown"), so only real name differences
# belong here. Keys and values must both be in normalized form.
NAME_ALIASES = {
    "hollywood brown": "marquise brown",
}


# --- Sleeper API ------------------------------------------------------------

def _get(path: str, timeout: int = 10):
    resp = requests.get(f"{BASE_URL}{path}", timeout=timeout)
    resp.raise_for_status()
    return resp.json()


def get_league(league_id: str) -> dict:
    data = _get(f"/league/{league_id}")
    if data is None:
        raise ValueError(f"No league found for league_id '{league_id}'")
    return data


def get_rosters(league_id: str) -> list:
    return _get(f"/league/{league_id}/rosters")


def get_drafts_for_league(league_id: str) -> list:
    return _get(f"/league/{league_id}/drafts")


def get_draft(draft_id: str) -> dict:
    data = _get(f"/draft/{draft_id}")
    if data is None:
        raise ValueError(f"No draft found for draft_id '{draft_id}'")
    return data


def get_draft_picks(draft_id: str) -> list:
    return _get(f"/draft/{draft_id}/picks")


def get_user(username: str) -> dict:
    data = _get(f"/user/{username}")
    if data is None:
        raise ValueError(f"No Sleeper user found for username '{username}'")
    return data


def get_all_players(force_refresh: bool = False) -> dict:
    if not force_refresh and os.path.exists(PLAYER_CACHE_PATH):
        age = time.time() - os.path.getmtime(PLAYER_CACHE_PATH)
        if age < PLAYER_CACHE_MAX_AGE:
            try:
                with open(PLAYER_CACHE_PATH) as f:
                    return json.load(f)
            except (json.JSONDecodeError, OSError):
                pass
    print("Downloading NFL player database (~5MB, cached 24h)...")
    players = _get("/players/nfl", timeout=60)
    try:
        os.makedirs(os.path.dirname(PLAYER_CACHE_PATH), exist_ok=True)
        with open(PLAYER_CACHE_PATH, "w") as f:
            json.dump(players, f)
    except OSError:
        pass
    return players


# --- Name matching ----------------------------------------------------------

def normalize_name(name: str) -> str:
    """Loose key so 'Marvin Harrison Jr.' matches 'Marvin Harrison'."""
    if not name:
        return ""
    cleaned = re.sub(r"[^a-z ]", "", name.lower())
    parts = [p for p in cleaned.split() if p and p not in NAME_SUFFIXES]
    key = " ".join(parts)
    return NAME_ALIASES.get(key, key)


def player_key(name: str, position: str) -> str:
    return f"{normalize_name(name)}|{(position or '').upper()}"


# --- Cheat sheet ------------------------------------------------------------

def save_cheatsheet(entries: list, source: str, path: str = CHEATSHEET_PATH) -> None:
    payload = {
        "source": source,
        "generated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "players": entries,
    }
    with open(path, "w") as f:
        json.dump(payload, f, indent=2)
    print(f"Saved {len(entries)} ranked players to {path} (source: {source})")


def load_cheatsheet(path: str = CHEATSHEET_PATH) -> dict:
    if not os.path.exists(path):
        return {}
    try:
        with open(path) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        print(f"Could not read {path}: {e}", file=sys.stderr)
        return {}


def index_cheatsheet(sheet: dict) -> dict:
    index = {}
    for entry in sheet.get("players", []):
        key = player_key(entry.get("name", ""), entry.get("pos", ""))
        if key not in index:
            index[key] = entry
    return index


def cheatsheet_from_csv(csv_path: str) -> list:
    name_cols = ("name", "player", "player_name", "playername", "full_name")
    pos_cols = ("pos", "position")
    rank_cols = ("rank", "rk", "overall", "adp", "ovr", "overall_rank")
    tier_cols = ("tier", "tiers")

    def find(header, options):
        lowered = {h.lower().strip().replace(" ", "_"): h for h in header}
        for opt in options:
            if opt in lowered:
                return lowered[opt]
        return None

    with open(csv_path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        header = reader.fieldnames or []
        name_col = find(header, name_cols)
        pos_col = find(header, pos_cols)
        rank_col = find(header, rank_cols)
        tier_col = find(header, tier_cols)

        if not name_col:
            raise ValueError(
                f"Could not find a name column in {csv_path}. Headers seen: {header}"
            )

        entries = []
        for i, row in enumerate(reader, 1):
            name = (row.get(name_col) or "").strip()
            if not name:
                continue
            pos = (row.get(pos_col) or "").strip().upper() if pos_col else ""
            # FantasyPros-style "RB1" position ranks -> plain position
            pos = re.sub(r"\d+$", "", pos)
            rank = i
            if rank_col:
                raw = (row.get(rank_col) or "").strip()
                try:
                    rank = int(float(raw))
                except ValueError:
                    rank = i
            tier = None
            if tier_col:
                raw = (row.get(tier_col) or "").strip()
                try:
                    tier = int(float(raw))
                except ValueError:
                    tier = None
            entries.append({"name": name, "pos": pos, "rank": rank, "tier": tier, "note": ""})

    entries.sort(key=lambda e: e["rank"])
    return entries


RESEARCH_SYSTEM = """You are scouting the current NFL season for a fantasy football draft.
Your training data predates this season, so use web search to establish the current
landscape.

Cover: this season's consensus top-150 draft order and ADP, backfield and target-share
roles that changed in the offseason, rookies with real projected roles, notable holdouts
or suspensions, and current injuries.

Write a dense scouting brief in plain prose — no JSON. Prioritize facts that would change
where a player is drafted. Be specific with names. Aim for roughly 1500 words."""


BOARD_SYSTEM = """You are converting a scouting brief into a fantasy football draft board.

Output ONLY a JSON array — no prose before or after, no markdown fences, no commentary.
Each element must be exactly:
  {"name": "Full Name", "pos": "RB", "team": "SF", "rank": 12, "tier": 3, "note": "<=8 words"}

Rules:
- "pos" is exactly one of QB, RB, WR, TE, K, DEF.
- "tier" groups players of similar value; a tier break means a real drop-off.
- "note" is a terse edge: role, risk, or upside. Under eight words.
- Player names must be exact and conventional — they are matched against a database.
- Emit every rank in the requested range and nothing outside it.
Start your response with [ and end it with ]."""


def run_prep(args) -> int:
    if args.from_csv:
        entries = cheatsheet_from_csv(args.from_csv)
        save_cheatsheet(entries, f"csv:{os.path.basename(args.from_csv)}", args.cheatsheet)
        verify_cheatsheet(args)
        return 0

    try:
        import anthropic
    except ImportError:
        print("The --prep mode needs the anthropic package: pip install anthropic",
              file=sys.stderr)
        return 1

    context = ""
    if args.league_id:
        try:
            league = get_league(args.league_id)
            active = {k: v for k, v in (league.get("scoring_settings") or {}).items() if v}
            context = (
                f"\n\nTailor the rankings to this league:\n"
                f"Roster slots: {league.get('roster_positions')}\n"
                f"Scoring (non-zero): {json.dumps(active)}\n"
                f"Teams: {league.get('total_rosters')}"
            )
        except requests.exceptions.RequestException:
            pass

    client = anthropic.Anthropic()
    research_path = args.cheatsheet + ".research.txt"

    # --- Phase 1: research only. No structured output competing for the budget. ---
    brief = ""
    if args.reuse_research and os.path.exists(research_path):
        with open(research_path) as f:
            brief = f.read()
        print(f"Reusing existing research brief ({len(brief)} chars) from {research_path}\n")
    else:
        print("Phase 1/2: researching the current season (a few minutes)...\n")
        brief = stream_call(
            client,
            system=RESEARCH_SYSTEM,
            user="Write the scouting brief." + context,
            max_tokens=12000,
            tools=[{"type": "web_search_20260209", "name": "web_search", "max_uses": 10}],
            show_text=False,
        )
        if not brief.strip():
            print("The research phase returned no text. Falling back to Sleeper's ordering:",
                  file=sys.stderr)
            print(f"  python {os.path.basename(__file__)} --prep --from-sleeper", file=sys.stderr)
            return 1
        with open(research_path, "w") as f:
            f.write(brief)
        print(f"\nResearch brief saved ({len(brief)} chars).\n")

    # --- Phase 2: convert to a board, in batches so no single call carries it all. ---
    print(f"Phase 2/2: building the board in batches of {args.batch}...\n")
    collected = []
    for start in range(1, args.size + 1, args.batch):
        end = min(start + args.batch - 1, args.size)
        print(f"  ranks {start}-{end} ... ", end="", flush=True)

        # Each batch is an independent call with no memory of the others, so it
        # will happily re-emit obvious names. Tell it what is already placed.
        taken = [e.get("name", "") for e in collected if e.get("name")]
        exclusion = ""
        if taken:
            exclusion = (
                "\n\nThese players are ALREADY on the board at earlier ranks. "
                "Do not include any of them again; continue past them:\n"
                + ", ".join(taken)
            )

        text = stream_call(
            client,
            system=BOARD_SYSTEM,
            user=(f"Scouting brief:\n\n{brief}\n\n"
                  f"Now emit overall ranks {start} through {end} as a JSON array."
                  + exclusion + context),
            max_tokens=8000,
            tools=None,
            show_text=False,
        )
        batch = parse_json_array(text) or []

        # Drop any repeats that slipped through, so the count printed is truthful.
        seen = {(normalize_name(e.get("name", "")), (e.get("pos") or "").upper())
                for e in collected}
        fresh = []
        for e in batch:
            key = (normalize_name(e.get("name", "")), (e.get("pos") or "").upper())
            if key in seen or not e.get("name"):
                continue
            seen.add(key)
            fresh.append(e)

        collected.extend(fresh)
        dupes = len(batch) - len(fresh)
        print(f"{len(fresh)} new" + (f" ({dupes} repeats dropped)" if dupes else ""))
        if not batch:
            with open(f"{args.cheatsheet}.batch{start}.raw.txt", "w") as f:
                f.write(text)

    if not collected:
        print("\nNo players recovered. Fall back to Sleeper's ordering:", file=sys.stderr)
        print(f"  python {os.path.basename(__file__)} --prep --from-sleeper", file=sys.stderr)
        return 1

    entries = normalize_entries(collected)
    print()
    save_cheatsheet(entries, "claude+websearch", args.cheatsheet)
    verify_cheatsheet(args)
    return 0


def stream_call(client, system, user, max_tokens, tools=None, show_text=False) -> str:
    """One streaming call. Reports why it stopped when it produces nothing."""
    request = {
        "model": MODEL,
        "max_tokens": max_tokens,
        "system": system,
        "messages": [{"role": "user", "content": user}],
    }
    if tools:
        request["tools"] = tools

    chunks = []
    final = None
    with client.messages.stream(**request) as stream:
        for event in stream:
            etype = getattr(event, "type", None)
            if etype == "text":
                chunks.append(event.text)
                if show_text:
                    print(event.text, end="", flush=True)
            elif etype == "content_block_start":
                bt = getattr(getattr(event, "content_block", None), "type", None)
                if bt == "server_tool_use":
                    print("[researching...]", flush=True)
        try:
            final = stream.get_final_message()
        except Exception:
            pass

    text = "".join(chunks)
    if not text.strip() and final is not None:
        reason = getattr(final, "stop_reason", "unknown")
        print(f"\n  (no text produced; stop_reason={reason})", file=sys.stderr)
        if reason == "max_tokens":
            print("  The token budget was consumed before any output was written.",
                  file=sys.stderr)
    return text


def run_prep_from_sleeper(args) -> int:
    """Build a cheat sheet from Sleeper's own player ordering. No API, no network
    beyond the player database you already cache. Always works."""
    players = get_all_players(force_refresh=args.refresh_players)

    pool = []
    for pid, p in players.items():
        pos = p.get("position")
        if pos not in FANTASY_POSITIONS or not p.get("team") or not p.get("active", True):
            continue
        sr = p.get("search_rank")
        if sr is None:
            continue
        name = p.get("full_name") or f"{p.get('first_name','')} {p.get('last_name','')}".strip()
        if not name:
            continue
        pool.append({"name": name, "pos": pos, "team": p.get("team"),
                     "rank": sr, "tier": None, "note": ""})

    pool.sort(key=lambda e: e["rank"])
    entries = normalize_entries(pool[:args.size])

    # Tier by gaps in Sleeper's ordering: a jump means a drop-off.
    for i, e in enumerate(entries):
        e["tier"] = i // 12 + 1

    save_cheatsheet(entries, "sleeper search_rank", args.cheatsheet)
    print("\nNote: this is Sleeper's own ordering, not researched rankings. "
          "It is a solid backbone but carries no injury/role context.")
    return 0


def run_repair(args) -> int:
    """Rebuild a cheat sheet from a saved raw response — no API call, no re-research."""
    raw_path = args.raw or (args.cheatsheet + ".raw.txt")
    if not os.path.exists(raw_path):
        print(f"No raw file at {raw_path}", file=sys.stderr)
        return 1

    with open(raw_path) as f:
        raw = f.read()

    entries = parse_json_array(raw)
    if not entries:
        print(f"Found no usable records in {raw_path}.", file=sys.stderr)
        print("Fall back to a rankings CSV: --prep --from-csv rankings.csv", file=sys.stderr)
        return 1

    entries = normalize_entries(entries)
    print(f"Recovered {len(entries)} players from {raw_path}")
    save_cheatsheet(entries, "claude+websearch (repaired)", args.cheatsheet)
    verify_cheatsheet(args)
    return 0


def parse_json_array(raw: str):
    """Tolerate stray prose, code fences, or a truncated/malformed array."""
    candidate = raw.strip()
    if candidate.startswith("```"):
        candidate = re.sub(r"^```(?:json)?\s*", "", candidate)
        candidate = re.sub(r"\s*```$", "", candidate)

    start, end = candidate.find("["), candidate.rfind("]")
    if start != -1 and end != -1:
        try:
            data = json.loads(candidate[start:end + 1])
            if isinstance(data, list) and data:
                return data
        except json.JSONDecodeError:
            pass  # fall through to object-by-object salvage

    salvaged = salvage_objects(candidate)
    return salvaged or None


def salvage_objects(raw: str) -> list:
    """Pull every complete {...} record out of the text.

    Survives a response that was truncated mid-array, wrapped in prose, or had
    one bad record in the middle — we keep every object that parses on its own.
    """
    entries = []
    depth = 0
    start = None
    in_string = False
    escaped = False

    for i, ch in enumerate(raw):
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                in_string = False
            continue
        if ch == '"':
            in_string = True
        elif ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}":
            if depth > 0:
                depth -= 1
                if depth == 0 and start is not None:
                    chunk = raw[start:i + 1]
                    try:
                        obj = json.loads(chunk)
                    except json.JSONDecodeError:
                        obj = None
                    if isinstance(obj, dict) and obj.get("name"):
                        entries.append(obj)
                    start = None
    return entries


def normalize_entries(entries: list) -> list:
    """Coerce salvaged records into the cheat sheet shape and re-rank cleanly."""
    cleaned = []
    for e in entries:
        name = str(e.get("name", "")).strip()
        if not name:
            continue
        pos = re.sub(r"\d+$", "", str(e.get("pos") or e.get("position") or "").strip().upper())
        try:
            rank = int(float(e.get("rank")))
        except (TypeError, ValueError):
            rank = None
        try:
            tier = int(float(e.get("tier")))
        except (TypeError, ValueError):
            tier = None
        cleaned.append({
            "name": name,
            "pos": pos,
            "rank": rank,
            "tier": tier,
            "note": str(e.get("note") or "")[:80],
            "team": str(e.get("team") or ""),
        })

    # Keep the model's ordering where ranks are missing or duplicated.
    ranked = [e for e in cleaned if e["rank"] is not None]
    unranked = [e for e in cleaned if e["rank"] is None]
    ranked.sort(key=lambda e: e["rank"])
    ordered = ranked + unranked

    seen = set()
    final = []
    for e in ordered:
        key = (normalize_name(e["name"]), e["pos"])
        if key in seen:
            continue
        seen.add(key)
        e["rank"] = len(final) + 1  # contiguous, so rank compares to pick numbers
        final.append(e)
    return final


def verify_cheatsheet(args) -> None:
    """Report how many cheat-sheet names actually match Sleeper's database."""
    sheet = load_cheatsheet(args.cheatsheet)
    entries = sheet.get("players", [])
    if not entries:
        return
    players = get_all_players()
    sleeper_keys = {
        player_key(
            p.get("full_name") or f"{p.get('first_name','')} {p.get('last_name','')}",
            p.get("position", ""),
        )
        for p in players.values()
        if p.get("position") in FANTASY_POSITIONS
    }
    unmatched = [e for e in entries if player_key(e.get("name",""), e.get("pos","")) not in sleeper_keys]
    matched = len(entries) - len(unmatched)
    print(f"Name match check: {matched}/{len(entries)} matched Sleeper's database.")
    if unmatched:
        print("Unmatched (these will fall back to Sleeper's own ordering):")
        for e in unmatched[:15]:
            print(f"  - {e.get('name')} ({e.get('pos')})")
        if len(unmatched) > 15:
            print(f"  ... and {len(unmatched) - 15} more")


# --- Snake draft math -------------------------------------------------------

def slot_for_pick(draft: dict, pick_no: int):
    teams = (draft.get("settings") or {}).get("teams")
    if not teams:
        return None
    round_no = (pick_no - 1) // teams + 1
    pos_in_round = (pick_no - 1) % teams + 1
    if draft.get("type") == "linear":
        return pos_in_round
    return pos_in_round if round_no % 2 == 1 else teams - pos_in_round + 1


def describe_pick(draft: dict, pick_no: int) -> str:
    teams = (draft.get("settings") or {}).get("teams") or 0
    if not teams:
        return f"#{pick_no}"
    rnd = (pick_no - 1) // teams + 1
    slot = (pick_no - 1) % teams + 1
    return f"{rnd}.{slot:02d} (#{pick_no})"


def my_upcoming_picks(draft: dict, next_pick_no: int, my_slot: int, count: int = 3) -> list:
    teams = (draft.get("settings") or {}).get("teams")
    rounds = (draft.get("settings") or {}).get("rounds") or 20
    if not teams or not my_slot:
        return []
    total = teams * rounds
    found, p = [], next_pick_no
    while p <= total and len(found) < count:
        if slot_for_pick(draft, p) == my_slot:
            found.append(p)
        p += 1
    return found


def my_slot_from_draft(draft: dict, my_user_id: str, my_roster_id=None):
    order = draft.get("draft_order") or {}
    if my_user_id in order:
        return order[my_user_id]
    if my_roster_id is not None:
        for slot, rid in (draft.get("slot_to_roster_id") or {}).items():
            if rid == my_roster_id:
                return int(slot)
    return None


# --- Roster analysis --------------------------------------------------------

def roster_positions_for(draft: dict, league: dict) -> list:
    if league and league.get("roster_positions"):
        return league["roster_positions"]
    settings = draft.get("settings") or {}
    return settings.get("roster_positions") or draft.get("roster_positions") or []


def compute_needs(roster_positions: list, my_positions: list) -> dict:
    required = Counter()
    flex_slots = 0
    superflex = False
    for slot in roster_positions:
        if slot in BENCH_SLOTS:
            continue
        if "FLEX" in slot:
            flex_slots += 1
            if "SUPER" in slot:
                superflex = True
        else:
            required[slot] += 1

    have = Counter(my_positions)
    need = {}
    for pos, req in required.items():
        short = req - have.get(pos, 0)
        if short > 0:
            need[pos] = short

    flex_pool = {"RB", "WR", "TE"} | ({"QB"} if superflex else set())
    surplus = sum(max(have.get(p, 0) - required.get(p, 0), 0) for p in flex_pool)
    flex_remaining = max(flex_slots - surplus, 0)
    if flex_remaining:
        need["FLEX"] = flex_remaining
    return need


FLEX_ELIGIBLE = {"RB", "WR", "TE"}


def positional_run(picks: list, players: dict, window: int = 10) -> Counter:
    counts = Counter()
    for pick in picks[-window:]:
        p = players.get(pick.get("player_id")) or {}
        if p.get("position") in FANTASY_POSITIONS:
            counts[p["position"]] += 1
    return counts


# --- Offline recommendation engine ------------------------------------------

def build_board(players: dict, drafted_ids: set, sheet_index: dict, limit: int = 80) -> list:
    """Available players, ranked by the cheat sheet where possible."""
    board = []
    for pid, p in players.items():
        if pid in drafted_ids:
            continue
        pos = p.get("position")
        if pos not in FANTASY_POSITIONS or not p.get("team") or not p.get("active", True):
            continue
        name = p.get("full_name") or f"{p.get('first_name','')} {p.get('last_name','')}".strip()
        entry = sheet_index.get(player_key(name, pos))
        if entry:
            rank = entry.get("rank") or 9999
            tier = entry.get("tier")
            note = entry.get("note") or ""
            ranked = True
        else:
            # Unranked players sort after everyone on the sheet, by Sleeper's order.
            sr = p.get("search_rank")
            rank = 10000 + (sr if sr is not None else 9999)
            tier = None
            note = ""
            ranked = False
        board.append({
            "player_id": pid, "name": name, "pos": pos, "team": p.get("team"),
            "rank": rank, "tier": tier, "note": note, "ranked": ranked,
            "injury": p.get("injury_status"),
        })
    board.sort(key=lambda x: x["rank"])
    return board[:limit]


def recommend(board: list, needs: dict, my_picks: list, next_pick_no: int,
              runs: Counter, top_n: int = 6) -> dict:
    """Pure local scoring: value, need, scarcity, and survival to the wrap."""
    if not board:
        return {"picks": [], "wait": [], "gone": []}

    wrap_pick = my_picks[1] if len(my_picks) > 1 else None
    # Players whose rank sits before our next-next pick are unlikely to survive it.
    survival_cutoff = wrap_pick if wrap_pick else next_pick_no + 12

    needed_positions = {p for p in needs if p != "FLEX"}
    if needs.get("FLEX"):
        needed_positions |= FLEX_ELIGIBLE

    scored = []
    for p in board:
        score = 1000.0 - p["rank"]           # base: board value
        if p["pos"] in needed_positions:
            score += 40                       # fills a hole in the starting lineup
        if runs.get(p["pos"], 0) >= 3:
            score += 15                       # position is running; supply draining
        gone_by_wrap = p["rank"] <= survival_cutoff
        if gone_by_wrap:
            score += 25                       # will not be there on the wrap
        if p["injury"]:
            score -= 10
        if not p["ranked"]:
            score -= 200                      # not on the cheat sheet; low confidence
        scored.append((score, gone_by_wrap, p))

    scored.sort(key=lambda t: -t[0])
    picks = [(s, g, p) for s, g, p in scored[:top_n]]
    wait = [p for s, g, p in scored[:25] if not g and p["ranked"]][:4]
    return {"picks": picks, "wait": wait, "survival_cutoff": survival_cutoff}


def render_recommendation(reco: dict, needs: dict, my_picks: list, draft: dict) -> None:
    print("=" * 64)
    print("RECOMMENDATION")
    print("=" * 64)
    if not reco["picks"]:
        print("No available players found.")
        return

    best_score, best_gone, best = reco["picks"][0]
    flag = "WILL NOT LAST" if best_gone else "safe-ish"
    note = f" — {best['note']}" if best["note"] else ""
    tier = f" T{best['tier']}" if best["tier"] else ""
    print(f"\n  PICK: {best['name']} ({best['pos']}, {best['team']}){tier}  [{flag}]{note}")

    print("\n  NEXT BEST:")
    for score, gone, p in reco["picks"][1:5]:
        tier = f" T{p['tier']}" if p["tier"] else ""
        mark = "gone by wrap" if gone else "may last"
        extra = f" — {p['note']}" if p["note"] else ""
        inj = f" [{p['injury']}]" if p["injury"] else ""
        print(f"    {p['name']} ({p['pos']}, {p['team']}){tier}{inj}  ({mark}){extra}")

    if reco["wait"]:
        print("\n  CAN WAIT (likely still there at your next pick):")
        for p in reco["wait"]:
            print(f"    {p['name']} ({p['pos']})")

    if len(my_picks) > 1:
        gap = my_picks[1] - my_picks[0] - 1
        print(f"\n  WRAP: after this you pick {describe_pick(draft, my_picks[1])} "
              f"— {gap} picks away. Anything ranked inside the top "
              f"{reco['survival_cutoff']} is unlikely to survive.")
    print()


# --- Live loop --------------------------------------------------------------

def run_live(args) -> int:
    sheet = load_cheatsheet(args.cheatsheet)
    if not sheet.get("players"):
        print(f"No cheat sheet found at {args.cheatsheet}.")
        print("Run the prep step first:")
        print(f"  python {os.path.basename(__file__)} --prep --league-id LEAGUE_ID")
        print("  (or --prep --from-csv rankings.csv)")
        print("\nContinuing with Sleeper's own ordering only — much weaker.\n")
        time.sleep(2)
    else:
        print(f"Cheat sheet: {len(sheet['players'])} players "
              f"(source: {sheet.get('source')}, built {sheet.get('generated_at')})")
    sheet_index = index_cheatsheet(sheet)

    league = None
    if args.league_id:
        league = get_league(args.league_id)
        drafts = get_drafts_for_league(args.league_id)
        if not drafts:
            print("No draft found for that league.", file=sys.stderr)
            return 1
        draft_id = drafts[0]["draft_id"]
    else:
        draft_id = args.draft_id

    draft = get_draft(draft_id)
    players = get_all_players(force_refresh=args.refresh_players)
    my_user = get_user(args.my_username)

    my_roster_id = None
    if args.league_id:
        rosters = get_rosters(args.league_id)
        my_roster = next(
            (
                r for r in rosters
                if r.get("owner_id") == my_user["user_id"]
                or my_user["user_id"] in (r.get("co_owners") or [])
            ),
            None,
        )
        my_roster_id = my_roster["roster_id"] if my_roster else None

    my_slot = my_slot_from_draft(draft, my_user["user_id"], my_roster_id)
    teams = (draft.get("settings") or {}).get("teams") or 0
    if my_slot:
        print(f"Drafting from slot {my_slot} of {teams}.")
    else:
        print("Draft order not assigned yet — Sleeper usually sets it just before the draft. "
              "Recommendations still work; the wrap math activates once your slot is known.")
    time.sleep(1.5)

    clear_cmd = "cls" if os.name == "nt" else "clear"

    while True:
        draft = get_draft(draft_id)
        picks = sorted(get_draft_picks(draft_id), key=lambda p: p.get("pick_no") or 0)
        next_pick_no = len(picks) + 1
        if my_slot is None:
            my_slot = my_slot_from_draft(draft, my_user["user_id"], my_roster_id)

        my_picks = my_upcoming_picks(draft, next_pick_no, my_slot) if my_slot else []
        drafted_ids = {p.get("player_id") for p in picks}

        my_own = [
            p for p in picks
            if (my_roster_id is not None and p.get("roster_id") == my_roster_id)
            or p.get("picked_by") == my_user["user_id"]
        ]
        my_positions = [
            pos for pos in
            ((players.get(p.get("player_id")) or {}).get("position") for p in my_own)
            if pos
        ]
        needs = compute_needs(roster_positions_for(draft, league), my_positions)
        runs = positional_run(picks, players)

        os.system(clear_cmd)
        print(f"=== {str(draft.get('status','?')).upper()} | {len(picks)} picks in | "
              f"on the clock: {describe_pick(draft, next_pick_no)} ===")
        if my_picks:
            away = my_picks[0] - next_pick_no
            you = "  <<< YOU ARE ON THE CLOCK" if away == 0 else f"  ({away} picks away)"
            print(f"Your next: {describe_pick(draft, my_picks[0])}{you}")
            if len(my_picks) > 1:
                print(f"Then:      {describe_pick(draft, my_picks[1])} "
                      f"({my_picks[1] - my_picks[0] - 1} picks in between)")

        roster_str = ", ".join(
            f"{(players.get(p.get('player_id')) or {}).get('full_name','?')}"
            f" ({(players.get(p.get('player_id')) or {}).get('position','?')})"
            for p in my_own
        )
        print(f"Your roster ({len(my_own)}): {roster_str or 'empty'}")
        print(f"Unfilled starters: {needs or 'none'}")
        if runs:
            print(f"Last 10 picks: {', '.join(f'{k} x{v}' for k, v in runs.most_common())}")
        print()

        board = build_board(players, drafted_ids, sheet_index)
        reco = recommend(board, needs, my_picks, next_pick_no, runs)
        render_recommendation(reco, needs, my_picks, draft)

        if args.once:
            return 0
        if draft.get("status") == "complete":
            print("Draft complete.")
            return 0
        time.sleep(args.poll)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--prep", action="store_true",
                        help="Build the cheat sheet (run once, before the draft)")
    parser.add_argument("--from-csv", help="Build the cheat sheet from a rankings CSV instead")
    parser.add_argument("--from-sleeper", action="store_true",
                        help="Build the cheat sheet from Sleeper's own ordering (no API, instant)")
    parser.add_argument("--repair", action="store_true",
                        help="Rebuild the cheat sheet from a saved raw response (no API call)")
    parser.add_argument("--raw", help="Raw response file to repair from")
    parser.add_argument("--size", type=int, default=200, help="How many players to rank (default 200)")
    parser.add_argument("--batch", type=int, default=50,
                        help="Players per generation call (default 50)")
    parser.add_argument("--reuse-research", action="store_true",
                        help="Skip re-researching; reuse the saved brief")
    parser.add_argument("--league-id", help="Sleeper league ID")
    parser.add_argument("--draft-id", help="Sleeper draft ID directly (mock drafts)")
    parser.add_argument("--my-username", help="Your Sleeper username (required for live mode)")
    parser.add_argument("--cheatsheet", default=CHEATSHEET_PATH,
                        help=f"Cheat sheet path (default {CHEATSHEET_PATH})")
    parser.add_argument("--poll", type=int, default=5, help="Seconds between polls (default 5)")
    parser.add_argument("--once", action="store_true",
                        help="Print one recommendation and exit (for testing)")
    parser.add_argument("--refresh-players", action="store_true", help="Force player DB re-download")
    args = parser.parse_args()

    try:
        if args.repair:
            return run_repair(args)
        if args.from_sleeper:
            return run_prep_from_sleeper(args)
        if args.prep or args.from_csv:
            return run_prep(args)

        if not args.my_username:
            parser.error("--my-username is required for live mode")
        if not (args.league_id or args.draft_id):
            parser.error("one of --league-id or --draft-id is required for live mode")
        return run_live(args)

    except KeyboardInterrupt:
        print("\nStopped.")
        return 0
    except requests.exceptions.RequestException as e:
        print(f"\nNetwork/API error (Sleeper): {e}", file=sys.stderr)
        return 1
    except ValueError as e:
        print(f"\n{e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
